-- File: drizzle/0011_useful_the_enforcers.sql

CREATE TABLE IF NOT EXISTS "hexmusic-stream_recommendation_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_recommendation_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255),
	"seedTrackIds" jsonb NOT NULL,
	"seedTrackData" jsonb NOT NULL,
	"recommendedTrackIds" jsonb NOT NULL,
	"recommendedTracksData" jsonb NOT NULL,
	"source" varchar(50) NOT NULL,
	"requestParams" jsonb,
	"responseTime" integer,
	"success" boolean NOT NULL,
	"errorMessage" text,
	"context" varchar(50),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'hexmusic-stream_recommendation_log_userId_hexmusic-stream_user_id_fk'
  ) THEN
    ALTER TABLE "hexmusic-stream_recommendation_log" ADD CONSTRAINT "hexmusic-stream_recommendation_log_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rec_log_user_idx" ON "hexmusic-stream_recommendation_log" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rec_log_source_idx" ON "hexmusic-stream_recommendation_log" USING btree ("source");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rec_log_created_idx" ON "hexmusic-stream_recommendation_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rec_log_success_idx" ON "hexmusic-stream_recommendation_log" USING btree ("success");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rec_log_context_idx" ON "hexmusic-stream_recommendation_log" USING btree ("context");
