// File: src/config/constants.ts

export const AUDIO_CONSTANTS = {

  TRACK_RESTART_THRESHOLD_SECONDS: 3,

  DEFAULT_VOLUME: 0.7,

  DEFAULT_PLAYBACK_RATE: 1,

  SEEK_JUMP_SECONDS: 10,

  AUTO_QUEUE_RETRY_DELAY_MS: 5000,
  AUTO_QUEUE_MIN_TRACKS: 5,
  AUTO_QUEUE_TARGET_SIZE: 8,

  QUEUE_PERSIST_DEBOUNCE_MS: 500,

  ARTWORK_SIZES: {
    SMALL: "56x56",
    MEDIUM: "250x250",
    BIG: "500x500",
    XL: "1000x1000",
  },

  AUDIO_LOAD_RETRY_DELAY_MS: 50,
} as const;

export const UI_CONSTANTS = {

  MIN_TOUCH_TARGET: 44,
  LARGE_TOUCH_TARGET: 48,

  ANIMATION_FAST: 150,
  ANIMATION_NORMAL: 300,
  ANIMATION_SLOW: 500,

  BREAKPOINTS: {
    MOBILE: 768,
    TABLET: 1024,
    DESKTOP: 1280,
  },

  DRAG_COLLAPSE_THRESHOLD: 100,
  DRAG_COLLAPSE_VELOCITY: 500,
} as const;

export const CACHE_CONSTANTS = {

  AUDIO_MAX_ENTRIES: 200,
  AUDIO_MAX_AGE_SECONDS: 60 * 60 * 24 * 30,

  IMAGE_MAX_ENTRIES: 200,
  IMAGE_MAX_AGE_SECONDS: 60 * 60 * 24 * 30,

  API_MAX_ENTRIES: 100,
  API_MAX_AGE_SECONDS: 60 * 60,
  API_TIMEOUT_SECONDS: 10,
} as const;

export const STORAGE_CONSTANTS = {

  QUOTA_WARNING_THRESHOLD: 80,

  QUOTA_CRITICAL_THRESHOLD: 95,
} as const;

export const NETWORK_CONSTANTS = {

  MAX_RETRY_ATTEMPTS: 3,

  RETRY_BASE_DELAY_MS: 1000,

  RETRY_MAX_DELAY_MS: 10000,
} as const;

export const VISUALIZER_CONSTANTS = {

  DEFAULT_FFT_SIZE: 128,

  DEFAULT_SMOOTHING: 0.8,

  MIN_DECIBELS: -90,

  MAX_DECIBELS: -10,
} as const;
